# 1. 시퀀스 자료형

In [2]:
#1.1 인덱싱
      #(-) 54321
          #01234
example = 'abcde'
print(example[0]) # 출력: a
print(example[2]) # 출력: c
print(example[-1])

a
c
e


In [3]:
# 1.2 슬라이싱
         #-54321
          #01234
example = 'abcde'
# print(example[:3]) # 출력: bc
print(example[-4:-1]) # 출력: bc

bc


In [4]:
# 1.3 특정항목 포함 여부
example = 'abcde'
print('a' in example) # 출력 : True

True


In [6]:
print('a' not in example)

False


In [5]:
print('z' in example) # 출력 : False

False


In [7]:
print('z' not in example)

True


In [8]:
# 1.4 연결 & 반복
example1 = 'abcde'
example2 = 'f'
print(example1 + example2)
print(example2 * 3)

abcdef


In [9]:
# 1.5 내장함수
# 기본 사용 : 함수(함수(변수 또는 인수))
example = 'abcde'
print(len(example))
print(min(example))
print(max(example))

5
a
e


#2. 시퀀스 자료형의 패킹과 언패킹

In [ ]:
# 패킹 : 그룹화
# 언패킹 : 분해

In [13]:
# 2.1 튜플 패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple) # 출력: (1, 2, 3,4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [14]:
tuple_example = 1
print(tuple_example)
type(tuple_example)

1


int

In [ ]:
# 2.2 언패킹

In [17]:
# 튜플 언패킹

# a, b, c, d = packed_tuple
# a, c, b, d = packed_tuple
a, b, c, d = packed_tuple
print(a)
print(b)
print(c)
print(d)

1
2
3
4


In [20]:
# 다양한 패킹/언패킹

# range : 0 부터 n-1까지 숫자를 생성하는 함수

# range(3)
# a = range(3) # 0, 1, 2
# print(a)

a, b, c = range(3) # 0, 1, 2
print(range(3))
print(a,b,c) # 언패킹을하면 순차적으로 숫자가 나옴

range(0, 3)
0 1 2


In [22]:
a, b, c, d, e = 'hello'
print(a)
print(b)
print(c)
print(d)
print(e)

h
e
l
l
o


In [21]:
a, b = [10, 20]
print(a)
print(b)

10
20


In [ ]:
# 언패킹은 시퀀스 자료형이라면 전부 활용 가능

In [25]:
total_sum = 0

for i in range(5):
    total_sum += i
    print(total_sum)

print(total_sum)

0
1
3
6
10
10


In [26]:
# 별표를 이용한 언패킹
first, *middle, last = [1,2,3,4,5]
print(first)
print(middle) # 출력: [2, 3, 4]
print(last)

1
[2, 3, 4]
5


In [28]:
# 별표를 이용한 언패킹
first, *middle = [1,2,3,4,5]
*middle, first = [1,2,3,4,5]
print(first)
print(middle) # 출력: [1, 2, 3, 4]

5
[1, 2, 3, 4]


In [ ]:
# 리스트

In [ ]:
# 리스트의 장점 : 여러가지 자료형을 넣을 수 있다

In [29]:
# 2.2 리스트 값 수정

a = [ 1, 2, 3, 4, 5]
a[0] = 10000
print(a)

[10000, 2, 3, 4, 5]


In [ ]:
# 리스트 항목 변경

In [38]:
# 문자열은 재할당으로 변경할 수 없다.
s = 'licat'
print(s[0])
s[0] = 'k'

l


TypeError: ignored

In [39]:
# 문자열을 굳이 변경하고 싶다면 replace를 사용
s = s.replace('l','k')
s

'kicat'

In [41]:
# 하지만 새 문자열을 새 변수에 할당하는 걸 권장
s2 = 'kicat'
s

'kicat'

In [42]:
b = [[10, 20, 30], [1, 2, 3]]
print(b[1][2]) # 출력: 3

3


In [43]:
print(b)
print(b[0])
print(b[1])
print(b[0][2])

[[10, 20, 30], [1, 2, 3]]
[10, 20, 30]
[1, 2, 3]
30


In [44]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [49]:
# 리스트의 덧셈
l = [1, 2, 3]
print(l)
print(type(l))
print(l * 3)
print(l + l)


[1, 2, 3]
<class 'list'>
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [48]:
import numpy as np

l = [1, 2, 3]
l = np.array(l)
print(l)
print(type(l))
print(l * 3)
print(l + l)


[1 2 3]
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [ ]:
# => 리스트는 원소 뒤에 이어서 원소가 추가되는 반면, numpy는 원소 별로 더해진다.
# 타입의 차이: 리스트 -> 'list, numpy -> numpy.ndarray
# 같은 [] 여도 list인지 numpy.ndarray인지 잘 구분해서 써야 한다.

In [50]:
lst = [1, 2, 3, 4, 5]
# lst[5] # error : list index out of range

IndexError: ignored

In [51]:
# 슬라이싱 실습!

l = [1, 2, 3, 4, 5]

print(l[:])


[1, 2, 3, 4, 5]


In [52]:
print(l[::-1])

[5, 4, 3, 2, 1]


In [53]:
print(l[::2])

[1, 3, 5]


In [54]:
print(l[0:4][::-1]) # 0~3 까지 인덱싱한것의 전체를 대상으로 거꾸로. 메서드 체이닝 비슷하게 생각

[4, 3, 2, 1]


In [ ]:
# 데이터가 크다. 내가 원하는 대로 데이터를 추출하고 싶다.!
# 1. 1억개 데이터 --- 샘플링 ---> 천개 정도 추출 -> 리스트 슬라이싱! 메서드! -> 1억개 데이터!

In [55]:
l = [1, 2, 3, 4, 5]
print(l[10:20]) # 출력 : []

[]
